### PR TITLE
Qualified Cursor Support

### PR DESCRIPTION
**Pull request by mpyw**
This PR makes it possible to use qualified cursor.

```php
$tags = Tag::find(1)->posts()->withPivot('id')
    ->lampager()
    ->forward()->limit(3)
    ->orderBy('posts.id')
    ->seekable()
    ->paginate(['posts.id' => 2]);
```

### CODE REVIEW

**Comment by chitoku-k** [comment]
The implementation looks fine but more tests can be added!

**Review by mpyw — COMMENTED** [review]
self-LGTM

**Comment by chitoku-k** [comment]
What is wrapped value mentioned in the commit message?

**Comment by mpyw** [comment]
@chitoku-k 

Wrapping means... alternatively "enclosed"

e.g.
- id --(wrap)--> \`id\`
- posts.id --(wrap)--> \`posts\`.\`id\`

`orderBy()` `orderByDesc()` can't accept already enclosed values.

**Review by chitoku-k — APPROVED** [review]
LGTM

**Pull request merged**
