### PR TITLE
Add compatibility for Laravel 5.5

### PR DESCRIPTION
**Pull request by alquerci**
Hello,

I found your library from https://github.com/nuwave/lighthouse/issues/311, and I see that it does not depends on HTTP request that's excellent for an API usage such as GraphQL.

I have a project using Laravel v5.5 without time frame for a framework upgrade.

Why
---

Sadly I see that currently Laravel version 5.5 is not supported on this library.

So I checkout quickly the effort to make it compatible.

I do not see a direct dependency on the implementation for `...\Resource` or `...\JsonResource`.

How
---

The class `Illuminate\Http\Resources\Json\Resource` extends `...\JsonResource` since Laravel version 5.5. But it is removed on version 7.0.

What I see about the limitation for Laravel 5.5 is only on tests suite.

Question
------

Does this compatibility can going to be possible?

Next
----

I also try to add Laravel 7 on travis.ci tests but I got this result with issue on date format.
https://travis-ci.org/github/alquerci/lampager-laravel/jobs/686051996

### CODE REVIEW

**Review by mpyw — COMMENTED** [review]
Thank you for submitting the PR!

Unfortunately, `Resource` is a soft-reserved word in the current PHP version. If we use the word in the source codes, it may cause Parse Error in the future versions. And Laravel 5.5 (LTS) will end its support term on this August.

Currently I'm not willing to merge the suggestion, sorry. Thank you anyway!

**Comment by alquerci** [comment]
Ha, yes, I miss this point about `resource`.

Pushed a better solution.

---

But you are free to close this PR if the following point take precedence.

> Laravel 5.5 (LTS) will end its support term on this August.

**Review by mpyw — APPROVED** [review]
LGTM

**Comment by alquerci** [comment]
@mpyw Thank you!

Nice picture.

**Pull request merged**
